// Package crypto verifies and produces Werkzeug-format password hashes.
//
// PRD reference: PRAGYA_GO_MIGRATION_PRD.md §8.2.
//
// This is BLOCKING for existing users. Rows already in farmers.password_hash
// cannot be re-hashed — the plaintext is gone — so Go must verify Werkzeug's
// format directly. Verified against fixtures generated by the real Python
// environment (internal/crypto/testdata/werkzeug_hashes.json); production rows
// on this deployment all use scrypt:32768:8:1.
package crypto

import (
	"crypto/rand"
	"crypto/sha1"
	"crypto/sha256"
	"crypto/sha512"
	"crypto/subtle"
	"encoding/hex"
	"errors"
	"fmt"
	"hash"
	"strconv"
	"strings"

	"golang.org/x/crypto/pbkdf2"
	"golang.org/x/crypto/scrypt"
)

// Werkzeug hash format is  <method>$<salt>$<hexdigest>  where method is either
//
//	scrypt:<N>:<r>:<p>          (Werkzeug >= 2.3 default, dkLen 64)
//	pbkdf2:<hash>:<iterations>  (dkLen 32 for sha256)
//
// The salt is used as its raw ASCII bytes, NOT decoded from hex or base64.
const (
	scryptDKLen  = 64
	pbkdf2DKLen  = 32
	saltLength   = 16
	saltAlphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
)

// ErrUnsupportedMethod is returned for a hash whose method prefix is unknown.
var ErrUnsupportedMethod = errors.New("unsupported password hash method")

// VerifyPassword reports whether plaintext matches a Werkzeug-format hash.
//
// The digest comparison is constant-time. A malformed hash is an error, not a
// silent false, so a corrupt row is distinguishable from a wrong password.
func VerifyPassword(encoded, plaintext string) (bool, error) {
	method, salt, want, err := split(encoded)
	if err != nil {
		return false, err
	}
	got, err := derive(method, salt, plaintext)
	if err != nil {
		return false, err
	}
	return subtle.ConstantTimeCompare([]byte(got), []byte(want)) == 1, nil
}

// GeneratePassword produces a Werkzeug-compatible scrypt hash, so that rows
// written by Go stay verifiable by the Python backend during the cutover and
// after a rollback.
func GeneratePassword(plaintext string) (string, error) {
	salt, err := randomSalt(saltLength)
	if err != nil {
		return "", err
	}
	const method = "scrypt:32768:8:1"
	digest, err := derive(method, salt, plaintext)
	if err != nil {
		return "", err
	}
	return method + "$" + salt + "$" + digest, nil
}

func split(encoded string) (method, salt, digest string, err error) {
	parts := strings.Split(encoded, "$")
	if len(parts) != 3 {
		return "", "", "", fmt.Errorf("malformed werkzeug hash: expected 3 $-separated parts, got %d", len(parts))
	}
	if parts[0] == "" || parts[2] == "" {
		return "", "", "", errors.New("malformed werkzeug hash: empty method or digest")
	}
	return parts[0], parts[1], parts[2], nil
}

// derive computes the hex digest for a method spec, salt and password.
func derive(method, salt, password string) (string, error) {
	switch {
	case strings.HasPrefix(method, "scrypt:"):
		n, r, p, err := scryptParams(method)
		if err != nil {
			return "", err
		}
		// Werkzeug passes the salt as raw ASCII bytes.
		key, err := scrypt.Key([]byte(password), []byte(salt), n, r, p, scryptDKLen)
		if err != nil {
			return "", fmt.Errorf("scrypt: %w", err)
		}
		return hex.EncodeToString(key), nil

	case strings.HasPrefix(method, "pbkdf2:"):
		h, iters, err := pbkdf2Params(method)
		if err != nil {
			return "", err
		}
		key := pbkdf2.Key([]byte(password), []byte(salt), iters, pbkdf2DKLen, h)
		return hex.EncodeToString(key), nil
	}
	return "", fmt.Errorf("%w: %q", ErrUnsupportedMethod, method)
}

// scryptParams parses "scrypt:N:r:p".
func scryptParams(method string) (n, r, p int, err error) {
	fields := strings.Split(method, ":")
	if len(fields) != 4 {
		return 0, 0, 0, fmt.Errorf("malformed scrypt method %q", method)
	}
	if n, err = strconv.Atoi(fields[1]); err != nil {
		return 0, 0, 0, fmt.Errorf("scrypt N in %q: %w", method, err)
	}
	if r, err = strconv.Atoi(fields[2]); err != nil {
		return 0, 0, 0, fmt.Errorf("scrypt r in %q: %w", method, err)
	}
	if p, err = strconv.Atoi(fields[3]); err != nil {
		return 0, 0, 0, fmt.Errorf("scrypt p in %q: %w", method, err)
	}
	return n, r, p, nil
}

// pbkdf2Params parses "pbkdf2:<hash>:<iterations>", defaulting to sha256 and
// Werkzeug's own default iteration count when the tail is omitted.
func pbkdf2Params(method string) (func() hash.Hash, int, error) {
	fields := strings.Split(method, ":")
	name := "sha256"
	iters := 600000
	if len(fields) >= 2 && fields[1] != "" {
		name = fields[1]
	}
	if len(fields) >= 3 && fields[2] != "" {
		var err error
		if iters, err = strconv.Atoi(fields[2]); err != nil {
			return nil, 0, fmt.Errorf("pbkdf2 iterations in %q: %w", method, err)
		}
	}
	switch name {
	case "sha256":
		return sha256.New, iters, nil
	case "sha512":
		return sha512.New, iters, nil
	case "sha1":
		return sha1.New, iters, nil
	}
	return nil, 0, fmt.Errorf("%w: pbkdf2 hash %q", ErrUnsupportedMethod, name)
}

// randomSalt matches Werkzeug's gen_salt: `length` characters drawn UNIFORMLY
// from [A-Za-z0-9] using a CSPRNG.
//
// Rejection sampling, not `b % 62`: 256 is not a multiple of 62, so the modulo
// would make the first eight letters ~25% likelier than the rest. Werkzeug uses
// secrets.choice, which is unbiased, and matching that keeps the full 16×log2(62)
// ≈ 95 bits of salt entropy.
func randomSalt(length int) (string, error) {
	// The largest multiple of the alphabet size that fits in a byte; draws at
	// or above it are discarded rather than folded, which is what removes the bias.
	limit := byte(256 - (256 % len(saltAlphabet)))

	out := make([]byte, 0, length)
	buf := make([]byte, length)
	for len(out) < length {
		if _, err := rand.Read(buf); err != nil {
			return "", err
		}
		for _, b := range buf {
			if b >= limit {
				continue
			}
			out = append(out, saltAlphabet[int(b)%len(saltAlphabet)])
			if len(out) == length {
				break
			}
		}
	}
	return string(out), nil
}
